name: Test Report
description: Detail test cases that need addressing
labels: ["bug"]
body:
- type: input
  attributes:
    label: Feature
    description: What feature are you testing?
    placeholder: "Example: summon new DAO"
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected outcome
    description: What did you expect to happen in testing this feature?
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual outcome
    description: What happened that didn't meet your expectations?
  validations:
    required: true
- type: dropdown
  attributes:
    label: Browser
    description: Which browser is this issue occuring in?
    multiple: true
    options:
      - label: N/A
      - label: Firefox
      - label: Chrome
      - label: Brave
      - label: Safari
      - label: Internet Explorer
      - label: Other
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    placeholder: "Place additional information or screenshots that will help address this issue here."
  validations:
    required: false
